#Please check the parameters, and adjust them according to your project needs.

# Project name
PROJECT: GENOMICON-Seq - Whole Exome Sequencing


# =======================================================
# ================= GENERAL PARAMETERS ==================
# =======================================================

NUM_SAMPLES: 1 
FRAG_REPLICATES: 3 
NCORE: 24  
SEED: "1998463932"
OUTPUT_DIRECTORY: "/usr/src/app/scratch/Output_data_7" 
INPUT_DIRECTORY: "/usr/src/app/pipeline/input_data"
FASTA_FILE: "chr1_only.fasta.gz" 


# =======================================================
# ================== SAMPLE PARAMETERS ==================
# =======================================================

# 1. GENOME COPIES IN THE SAMPLE
# ==============================

NR_COPIES: "2500" 
MULTIFASTA_COPIES_TABLE: "" 

# 2. MUTATION TARGETS
# ===================

MUT_CONTEXT: "TCA,TCT,TCG,TCC" 

# 3. SUBSTITUTION TYPE
# ====================

TS_TV_RATIO: "3:1" 
SUBSTITUTION_PROBABILITY_TABLE: "" 

# 4. MUTATION MODE
# ================

# 4.a DETERMINISTIC MODE
# ======================

MUT_GENOME_FRACTION: "0.4" 
FRACTION_POSITION: "0.005" 

# 4.b SPECIFIC MUTATION RATE MODE
# ===============================

MUTATION_RATE: "" 

# 4.c SBS-MIMICRY MODE 
# ===============================

SBS_SIGNATURES: ""


# =============================================================
# ================== FRGMENTATION PARAMETERS ==================
# =============================================================

FRAGMENT_FRACTION: ""
MIN_FRAGMENT_LENGTH: "250" 
MAX_FRAGMENT_LENGTH: "1000" 

# ==============================================================
# ================== PROBE CAPTURE ENRICHMENT ==================
# ==============================================================
PROBES_FASTA: ""
PROBES_BED: "xgen-exome-research-panel-v2-probes-hg38_filtered_chr1.bed" #probe binding coordinates
PROBES_TARGES: "xgen-exome-research-panel-v2-targets-hg38_filtered_chr1.bed" # regions which probes target - it can also be 
MATCHING_LENGTH: "100" 

# ====================================================
# ================== PCR PARAMETERS ==================
# ====================================================

NUM_CYCLES: "8"

# ADVANCED PCR PARAMETERES
# ========================

K_PARAMETER_pcr: "0.3" 
MIDPOINT_CYCLE: "20" 

# ==========================================================
# ================= SEQUENCING PARAMETERS ==================
# ==========================================================

NUM_READS: "35000000" 
MODE: ""
ERROR_MODEL: "novaseq" 
FASTA_GZ_OUTPUT: "--compress" 
GC_BIAS: ""
OPT_FRAG_LENGTH: "NO"

# ADVANCED SEQUENCING PARAMETER
# =============================
K_PARAMETER_seq: "0.05" 
