#Please check the parameters, and adjust them according to your project needs.

# Project name
PROJECT: IS-WES


# ================= General arguments ==================

NUM_SAMPLES: 1 
FRAG_REPLICATES: 1 
NCORE: 58  
SEED: ""  
OUTPUT_DIRECTORY: "/usr/src/app/scratch/Output_data_7"
INPUT_DIRECTORY: "/usr/src/app/pipeline/input_data"
FASTA_FILE: "human_genome.fasta.gz" 
SBS_SIGNATURES: "sbs92_short.csv"

# ================== Configuration for 1defining_seq_and_mut ==================

MUT_CONTEXT: ""
TS_TV_RATIO: "" 
VARIANT_PROBABILITY_TABLE: "" 
NR_COPIES: "1000" 
MULTIFASTA_COPIES: "" 
MUT_GENOME_FRACTION: "0.8" 
FRACTION_POSITION: "0.03" 
MUTATION_RATE: "" 


# ================== Whole Human Exom or Specific probes ==================
PROBES_FASTA: ""
PROBES_BED: "xgen-exome-research-panel-v2-probes-hg38_short_all.bed" #probe binding coordinates
PROBES_TARGES: "xgen-exome-research-panel-v2-targets-hg38_short_all.bed" # regions which probes target

# ================== Configuration for Fragmentation  ==================

FRAGMENT_FRACTION: ""
MIN_FRAGMENT_LENGTH: "250" 
MAX_FRAGMENT_LENGTH: "1000" 
MATCHING_LENGTH: "100" 

# ================== Configuration for PCR ==================

K_PARAMETER_pcr: "0.3" 
MIDPOINT_CYCLE: "20" 
NUM_CYCLES: "8"

# ================= Sequencing Parameteres ==================

NUM_READS: "35000000"
MODE: ""
ERROR_MODEL: "novaseq" 
FASTA_GZ_OUTPUT: "--compress" 
OPT_FRAG_MODE: "median" 
K_PARAMETER_seq: "0.05" 
